In [69]:
import pandas as pd

data=pd.read_csv('df_fin.csv')

In [70]:
data

Date                                           기사제목    Close  \
0     2021-01-01  [낡은규제혁파①]"세계 최고 상속세율, 기업인에 사망선고"…재계, 상속세율 ...  83000.0   
1     2021-01-01            [낡은규제혁파①]암세포 같은 낡은 규제가 한국 경제 혁신 막는다  83000.0   
2     2021-01-01           머리카락 100배 얇은 초박막렌즈 개발…스마트폰 `카툭튀` 없앤다  83000.0   
3     2021-01-01             1월효과, 연말랠리 잇는다…증권가 "실적개선·경기민감株 주목"  83000.0   
4     2021-01-01  [낡은규제혁파①]"세계 최고 상속세율, 기업인에 사망선고"…재계, 상속세율 ...  83000.0   
...          ...                                            ...      ...   
5479  2021-06-29                  삼성전자 "美공장부지 선정 못했다"…핵심은 '칩스법'  80700.0   
5480  2021-06-29         삼성 'SSAFY'·SK '하이파이브'…정부 지원으로 3천명+α 확대  80700.0   
5481  2021-06-29               삼성전자, 2Q 영업익 11조원 초반대…반도체 견인-IBK  80700.0   
5482  2021-06-29               삼성·LG전자, 2분기 실적도 '훨훨'…내주 잠정실적 발표  80700.0   
5483  2021-06-29        삼성전자, 사내외 벤처 인큐베이팅 가동…5년동안 500개 프로젝트 육성  80700.0   

        Change   등락구분  label  주가 반영 Date  
0     0.024691   True    1.0  2021-01-04  
1     0.024691   True    1.0  2021-01-04  
2     0.024691   True    1.0  2021-01-04  
3     0.024691   True    1.0  2021-01-04  
4     0.024691   True    1.0  2021-01-04  
...        ...    ...    ...         ...  
5479 -0.003704  False   -1.0  2021-06-30  
5480 -0.003704  False   -1.0  2021-06-30  
5481 -0.003704  False   -1.0  2021-06-30  
5482 -0.003704  False   -1.0  2021-06-30  
5483 -0.003704  False   -1.0  2021-06-30  

[5484 rows x 7 columns]

# Okt

https://colab.research.google.com/drive/1FfhWsP9izQcuVl06P30r5cCxELA1ciVE?usp=sharing#scrollTo=fVSpOZIoYOOJ

In [51]:
from konlpy.tag import Okt
from nltk.tokenize import word_tokenize 
import re
okt=Okt()

In [64]:
stopwords='아 휴 아이구 아이쿠 아이고 어 나 우리 저희 따라 의해 을 를 에 의 가 으로 로 에게 뿐이다 의거하여 근거하여 입각하여 기준으로 예하면 예를 들면 예를 들자면 저 소인 소생 저희 지말고 하지마 하지마라 다른 물론 또한 그리고 비길수 없다 해서는 안된다 뿐만 아니라 만이 아니다 만은 아니다 막론하고 관계없이 그치지 않다 그러나 그런데 하지만 든간에 논하지 않다 따지지 않다 설사 비록 더라도 아니면 만 못하다 하는 편이 낫다 불문하고 향하여 향해서 향하다 쪽으로 틈타 이용하여 타다 오르다 제외하고 이 외에 이 밖에 하여야 비로소 한다면 몰라도 외에도 이곳 여기 부터 기점으로 따라서 할 생각이다 하려고하다 이리하여 그리하여 그렇게 함으로써 하지만 일때 할때 앞에서 중에서 보는데서 으로써 로써 까지 해야한다 일것이다 반드시 할줄알다 할수있다 할수있어 임에 틀림없다 한다면 등 등등 제 겨우 단지 다만 할뿐 딩동 댕그 대해서 대하여 대하면 훨씬 얼마나 얼마만큼 얼마큼 남짓 여 얼마간 약간 다소 좀 조금 다수 몇 얼마 지만 하물며 또한 그러나 그렇지만 하지만 이외에도 대해 말하자면 뿐이다 다음에 반대로 반대로 말하자면 이와 반대로 바꾸어서 말하면 바꾸어서 한다면 만약 그렇지않으면 까악 툭 딱 삐걱거리다 보드득 비걱거리다 꽈당 응당 해야한다 에 가서 각 각각 여러분 각종 각자 제각기 하도록하다 와 과 그러므로 그래서 고로 한 까닭에 하기 때문에 거니와 이지만 대하여 관하여 관한 과연 실로 아니나다를가 생각한대로 진짜로 한적이있다 하곤하였다 하 하하 허허 아하 거바 와 오 왜 어째서 무엇때문에 어찌 하겠는가 무슨 어디 어느곳 더군다나 하물며 더욱이는 어느때 언제 야 이봐 어이 여보시오 흐흐 흥 휴 헉헉 헐떡헐떡 영차 여차 어기여차 끙끙 아야 앗 아야 콸콸 졸졸 좍좍 뚝뚝 주룩주룩 솨 우르르 그래도 또 그리고 바꾸어말하면 바꾸어말하자면 혹은 혹시 답다 및 그에 따르는 때가 되어 즉 지든지 설령 가령 하더라도 할지라도 일지라도 지든지 몇 거의 하마터면 인젠 이젠 된바에야 된이상 만큼 어찌됏든 그위에 게다가 점에서 보아 비추어 보아 고려하면 하게될것이다 일것이다 비교적 좀 보다더 비하면 시키다 하게하다 할만하다 의해서 연이서 이어서 잇따라 뒤따라 뒤이어 결국 의지하여 기대여 통하여 자마자 더욱더 불구하고 얼마든지 마음대로 주저하지 않고 곧 즉시 바로 당장 하자마자 밖에 안된다 하면된다 그래 그렇지 요컨대 다시 말하자면 바꿔 말하면 즉 구체적으로 말하자면 시작하여 시초에 이상 허 헉 허걱 바와같이 해도좋다 해도된다 게다가 더구나 하물며 와르르 팍 퍽 펄렁 동안 이래 하고있었다 이었다 에서 로부터 까지 예하면 했어요 해요 함께 같이 더불어 마저 마저도 양자 모두 습니다 가까스로 하려고하다 즈음하여 다른 다른 방면으로 해봐요 습니까 했어요 말할것도 없고 무릎쓰고 개의치않고 하는것만 못하다 하는것이 낫다 매 매번 들 모 어느것 어느 로써 갖고말하자면 어디 어느쪽 어느것 어느해 어느 년도 라 해도 언젠가 어떤것 어느것 저기 저쪽 저것 그때 그럼 그러면 요만한걸 그래 그때 저것만큼 그저 이르기까지 할 줄 안다 할 힘이 있다 너 너희 당신 어찌 설마 차라리 할지언정 할지라도 할망정 할지언정 구토하다 게우다 토하다 메쓰겁다 옆사람 퉤 쳇 의거하여 근거하여 의해 따라 힘입어 그 다음 버금 두번째로 기타 첫번째로 나머지는 그중에서 견지에서 형식으로 쓰여 입장에서 위해서 단지 의해되다 하도록시키다 뿐만아니라 반대로 전후 전자 앞의것 잠시 잠깐 하면서 그렇지만 다음에 그러한즉 그런즉 남들 아무거나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 어떻게 만약 만일 위에서 서술한바와같이 인 듯하다 하지 않는다면 만약에 무엇 무슨 어느 어떤 아래윗 조차 한데 그럼에도 불구하고 여전히 심지어 까지도 조차도 하지 않도록 않기 위하여 때 시각 무렵 시간 동안 어때 어떠한 하여금 네 예 우선 누구 누가 알겠는가 아무도 줄은모른다 줄은 몰랏다 하는 김에 겸사겸사 하는바 그런 까닭에 한 이유는 그러니 그러니까 때문에 그 너희 그들 너희들 타인 것 것들 너 위하여 공동으로 동시에 하기 위하여 어찌하여 무엇때문에 붕붕 윙윙 나 우리 엉엉 휘익 윙윙 오호 아하 어쨋든 만 못하다 하기보다는 차라리 하는 편이 낫다 흐흐 놀라다 상대적으로 말하자면 마치 아니라면 쉿 그렇지 않으면 그렇지 않다면 안 그러면 아니었다면 하든지 아니면 이라면 좋아 알았어 하는것도 그만이다 어쩔수 없다 하나 일 일반적으로 일단 한켠으로는 오자마자 이렇게되면 이와같다면 전부 한마디 한항목 근거로 하기에 아울러 하지 않도록 않기 위해서 이르기까지 이 되다 로 인하여 까닭으로 이유만으로 이로 인하여 그래서 이 때문에 그러므로 그런 까닭에 알 수 있다 결론을 낼 수 있다 으로 인하여 있다 어떤것 관계가 있다 관련이 있다 연관되다 어떤것들 에 대해 이리하여 그리하여 여부 하기보다는 하느니 하면 할수록 운운 이러이러하다 하구나 하도다 다시말하면 다음으로 에 있다 에 달려 있다 우리 우리들 오히려 하기는한데 어떻게 어떻해 어찌됏어 어때 어째서 본대로 자 이 이쪽 여기 이것 이번 이렇게말하자면 이런 이러한 이와 같은 요만큼 요만한 것 얼마 안 되는 것 이만큼 이 정도의 이렇게 많은 것 이와 같다 이때 이렇구나 것과 같이 끼익 삐걱 따위 와 같은 사람들 부류의 사람들 왜냐하면 중의하나 오직 오로지 에 한하다 하기만 하면 도착하다 까지 미치다 도달하다 정도에 이르다 할 지경이다 결과에 이르다 관해서는 여러분 하고 있다 한 후 혼자 자기 자기집 자신 우에 종합한것과같이 총적으로 보면 총적으로 말하면 총적으로 대로 하다 으로서 참 그만이다 할 따름이다 쿵 탕탕 쾅쾅 둥둥 봐 봐라 아이야 아니 와아 응 아이 참나 년 월 일 령 영 일 이 삼 사 오 육 륙 칠 팔 구 이천육 이천칠 이천팔 이천구 하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 령 영 이 있 하 것 들 그 되 수 이 보 않 없 나 사람 주 아니 등 같 우리 때 년 가 한 지 대하 오 말 일 그렇 위하 때문 그것 두 말하 알 그러나 받 못하 일 그런 또 문제 더 사회 많 그리고 좋 크 따르 중 나오 가지 씨 시키 만들 지금 생각하 그러 속 하나 집 살 모르 적 월 데 자신 안 어떤 내 내 경우 명 생각 시간 그녀 다시 이런 앞 보이 번 나 다른 어떻 여자 개 전 들 사실 이렇 점 싶 말 정도 좀 원 잘 통하 놓'

stopwords=stopwords.split(' ')

In [62]:
stopwords

['아',
 '휴',
 '아이구',
 '아이쿠',
 '아이고',
 '어',
 '나',
 '우리',
 '저희',
 '따라',
 '의해',
 '을',
 '를',
 '에',
 '의',
 '가',
 '으로',
 '로',
 '에게',
 '뿐이다',
 '의거하여',
 '근거하여',
 '입각하여',
 '기준으로',
 '예하면',
 '예를',
 '들면',
 '예를',
 '들자면',
 '저',
 '소인',
 '소생',
 '저희',
 '지말고',
 '하지마',
 '하지마라',
 '다른',
 '물론',
 '또한',
 '그리고',
 '비길수',
 '없다',
 '해서는',
 '안된다',
 '뿐만',
 '아니라',
 '만이',
 '아니다',
 '만은',
 '아니다',
 '막론하고',
 '관계없이',
 '그치지',
 '않다',
 '그러나',
 '그런데',
 '하지만',
 '든간에',
 '논하지',
 '않다',
 '따지지',
 '않다',
 '설사',
 '비록',
 '더라도',
 '아니면',
 '만',
 '못하다',
 '하는',
 '편이',
 '낫다',
 '불문하고',
 '향하여',
 '향해서',
 '향하다',
 '쪽으로',
 '틈타',
 '이용하여',
 '타다',
 '오르다',
 '제외하고',
 '이',
 '외에',
 '이',
 '밖에',
 '하여야',
 '비로소',
 '한다면',
 '몰라도',
 '외에도',
 '이곳',
 '여기',
 '부터',
 '기점으로',
 '따라서',
 '할',
 '생각이다',
 '하려고하다',
 '이리하여',
 '그리하여',
 '그렇게',
 '함으로써',
 '하지만',
 '일때',
 '할때',
 '앞에서',
 '중에서',
 '보는데서',
 '으로써',
 '로써',
 '까지',
 '해야한다',
 '일것이다',
 '반드시',
 '할줄알다',
 '할수있다',
 '할수있어',
 '임에',
 '틀림없다',
 '한다면',
 '등',
 '등등',
 '제',
 '겨우',
 '단지',
 '다만',
 '할뿐',
 '딩동',
 '댕그',
 '대해서',
 '대하여',
 '대하면',


In [78]:
lists=[]
for i in range(len(data['Date'])):
    text=data.iloc[i]['기사제목']
    text=re.sub(r'[@%\\*=()/~#&\+á?\xc3\xa1\-\|\.\:\;\!\-\,\_\~\$\'\"]','',text)
    text = re.sub(r'\d+','',text)# remove number
    text = text.lower() #lower case
    text = re.sub(r'\s+', ' ', text) #remove extra space
    text = re.sub(r'<[^>]+>','',text) #remove Html tags
    text = re.sub(r'\s+', ' ', text) #remove spaces
    text = re.sub(r"^\s+", '', text) #remove space from start
    text = re.sub(r'\s+$', '', text)
    hangul = re.compile('[^ ㄱ-ㅣ가-힣]+')
    result=hangul.sub('',text)
    if result not in stopwords:
        results=okt.morphs(result)
        lists.append(results)
        
    
data['형태소분석']=lists

In [79]:
data

Date                                           기사제목    Close  \
0     2021-01-01  [낡은규제혁파①]"세계 최고 상속세율, 기업인에 사망선고"…재계, 상속세율 ...  83000.0   
1     2021-01-01            [낡은규제혁파①]암세포 같은 낡은 규제가 한국 경제 혁신 막는다  83000.0   
2     2021-01-01           머리카락 100배 얇은 초박막렌즈 개발…스마트폰 `카툭튀` 없앤다  83000.0   
3     2021-01-01             1월효과, 연말랠리 잇는다…증권가 "실적개선·경기민감株 주목"  83000.0   
4     2021-01-01  [낡은규제혁파①]"세계 최고 상속세율, 기업인에 사망선고"…재계, 상속세율 ...  83000.0   
...          ...                                            ...      ...   
5479  2021-06-29                  삼성전자 "美공장부지 선정 못했다"…핵심은 '칩스법'  80700.0   
5480  2021-06-29         삼성 'SSAFY'·SK '하이파이브'…정부 지원으로 3천명+α 확대  80700.0   
5481  2021-06-29               삼성전자, 2Q 영업익 11조원 초반대…반도체 견인-IBK  80700.0   
5482  2021-06-29               삼성·LG전자, 2분기 실적도 '훨훨'…내주 잠정실적 발표  80700.0   
5483  2021-06-29        삼성전자, 사내외 벤처 인큐베이팅 가동…5년동안 500개 프로젝트 육성  80700.0   

        Change   등락구분  label  주가 반영 Date  \
0     0.024691   True    1.0  2021-01-04   
1     0.024691   True    1.0  2021-01-04   
2     0.024691   True    1.0  2021-01-04   
3     0.024691   True    1.0  2021-01-04   
4     0.024691   True    1.0  2021-01-04   
...        ...    ...    ...         ...   
5479 -0.003704  False   -1.0  2021-06-30   
5480 -0.003704  False   -1.0  2021-06-30   
5481 -0.003704  False   -1.0  2021-06-30   
5482 -0.003704  False   -1.0  2021-06-30   
5483 -0.003704  False   -1.0  2021-06-30   

                                                  형태소분석  
0     [낡은, 규, 제혁, 파세계, 최고, 상속, 세율, 기업인, 에, 사망, 선고, 재...  
1     [낡은, 규, 제혁, 파, 암세포, 같은, 낡은, 규제, 가, 한국, 경제, 혁신,...  
2        [머리카락, 배, 얇은, 초, 박막, 렌즈, 개발, 스마트폰, 카툭, 튀, 없앤다]  
3       [월, 효과, 연말, 랠리, 잇는다, 증권, 가, 실적, 개선, 경기, 민감, 주목]  
4     [낡은, 규, 제혁, 파세계, 최고, 상속, 세율, 기업인, 에, 사망, 선고, 재...  
...                                                 ...  
5479          [삼성, 전자, 공장, 부지, 선정, 못, 했다, 핵심, 은, 칩스, 법]  
5480                    [삼성, 하이파이브, 정부, 지원, 으로, 천명, 확대]  
5481                [삼성, 전자, 영업, 익, 조원, 초반, 대, 반도체, 견인]  
5482            [삼성, 전자, 분기, 실적, 도, 훨훨, 내주, 잠정, 실적, 발표]  
5483  [삼성, 전자, 사, 내외, 벤, 처, 인큐, 베이, 팅, 가동, 년, 동안, 개,...  

[5484 rows x 8 columns]

In [80]:
news_title=data['형태소분석']

In [93]:
news_title[1][1]

'규'

In [102]:
news_list=[]
for i in range(len(news_title)):
    list1=[]
    for j in range(len(news_title[i])):
        list1.append(news_title[i][j])
    news_list.append(' '.join(list1))
news_list

['낡은 규 제혁 파세계 최고 상속 세율 기업인 에 사망 선고 재계 상속 세율',
 '낡은 규 제혁 파 암세포 같은 낡은 규제 가 한국 경제 혁신 막는다',
 '머리카락 배 얇은 초 박막 렌즈 개발 스마트폰 카툭 튀 없앤다',
 '월 효과 연말 랠리 잇는다 증권 가 실적 개선 경기 민감 주목',
 '낡은 규 제혁 파세계 최고 상속 세율 기업인 에 사망 선고 재계 상속 세율',
 '갤럭시 이번 엔 티저 영상 유출 새로운 갤럭시 가 기다리고 있다',
 '밑줄 쫙 국정 농단 대미 장식 특검 이재용 에 징역 년 구형',
 '코스피 시 총 사상 최초 넘어선 듯 삼전 조원 증가',
 '경제 기상도 코로나 에 갇혔던 경제 소의 뿔 처럼 저돌 적 돌파 기대',
 '반도체 메모리 값 강세 지 속 파운드리 수요 도 늘듯',
 '디스플레이 더 선명해진 프리미엄 시장 선점',
 '가전 집콕 수혜 백색 가전 상반기 까지 돌풍 예고',
 '스마트폰 중 저가 폰 라인업 확대 두 자릿수 성장 노려',
 '애플 폰 출시 두 달새 삼성 판매량 추월',
 '주식 부호 조 클럽 명 김범수 카카오 의장 순위 껑충',
 '장기 자의 비사 이드 크리스마스 는 아이폰 이 접수',
 '애플 카 전자 의 야심작 롤러 블 이 달 첫 선 어떻게 생겼나',
 '슈퍼 리치 재테크 스타 가 조언 하는 올해 주목 할 테마',
 '품질 로 경쟁 선언 반년 만에 명칭 놓고 삼성 신 경전',
 '대 그룹 시무 식 일 온라인 개최 이재용 신년사 없을 듯',
 '장기 자의 비사 이드 크리스마스 는 아이폰 이 접수',
 '주목 스몰 캡 살아나는 반도체 업황 기회 찾아온 아이 원스',
 '유 안타 주간 추천 주 매출 반등 예상 삼 성전 자 아모레퍼시픽 엔씨 소프',
 '단독 주린이 삼성로 몰리나 현대차 배터리 공급 후보 낙점',
 '삼성 전자 여전히 저 평가 전문가 새해 톱픽 추천',
 '삼성 패스 로 연말정산 을 전자서명 시장 본격 진출',
 '국내 가입자 천만 명 돌파 올해 대중화 단계',
 '펀드 와 치 사상 최고 치 코스

# DTM

In [103]:
from sklearn.feature_extraction.text import CountVectorizer

DTM_vector = CountVectorizer()
X_train_DTM = DTM_vector.fit_transform(news_list)
print(X_train_DTM.shape)

(5484, 7794)


In [104]:
print(len(DTM_vector.get_feature_names()))

7794


In [105]:
print(DTM_vector.get_feature_names())

['가격', '가고', '가구', '가까운', '가까워서', '가까워졌', '가까워졌다', '가까이', '가나', '가는', '가능', '가능성', '가능하다', '가능한', '가능한가', '가능한가요', '가능할', '가능할까', '가능해져', '가능해진다', '가능했다', '가니', '가닥', '가덕도', '가던트', '가동', '가드', '가드닝', '가득한', '가뜩이나', '가라', '가려라', '가려진', '가로', '가르는', '가르치기만', '가를', '가린다', '가면', '가뭄', '가벼워져도', '가볍', '가볍게', '가볍다', '가보', '가보니', '가볼까', '가비', '가상', '가상현실', '가석방', '가선', '가성', '가세', '가속', '가수', '가스', '가스전', '가슴', '가시', '가신', '가야', '가업승계', '가에', '가에서', '가열', '가요', '가용', '가위', '가유', '가을', '가입', '가입자', '가자', '가장', '가장자리', '가전', '가전으', '가전제품', '가정', '가져야', '가져온', '가족', '가족사', '가즈', '가지', '가진', '가짜', '가치', '가치주', '가폰', '가하나', '가하는', '가회', '각각', '각계', '각광', '각양각색', '각자', '각종', '간다', '간담', '간만', '간문제', '간부', '간섭', '간접', '간증', '간청', '간판', '간편한', '갇혔던', '갇힌', '갈것', '갈것담', '갈길', '갈까', '갈등', '갈랐다', '갈린다', '갈릴까', '갈림길', '갈수', '갈아타는', '감각', '감독', '감면', '감사', '감산', '감상', '감성', '감세', '감소', '감속', '감시', '감안', '감염', '감염병', '감자', '감정', '감축', '감탄', '갑니다', '갑자기', '값싼', '갔다', '갔다가', '갔어야', '강경', '강국', '강남', '강력', '강력

In [106]:
print(X_train_DTM.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [107]:
review_DTM = pd.DataFrame(X_train_DTM.toarray(), columns = DTM_vector.get_feature_names())

In [108]:
review_DTM['label'] = data['label']

In [109]:
review_DTM

가격  가고  가구  가까운  가까워서  가까워졌  가까워졌다  가까이  가나  가는  ...  힐스  힐스테이트  힘껏  힘든  \
0      0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
1      0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
2      0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
3      0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
4      0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
...   ..  ..  ..  ...   ...   ...    ...  ...  ..  ..  ...  ..    ...  ..  ..   
5479   0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
5480   0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
5481   0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
5482   0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   
5483   0   0   0    0     0     0      0    0   0   0  ...   0      0   0   0   

      힘들까  힘들어  힘쓰는  힘찬  힙합  label  
0       0    0    0   0   0    1.0  
1       0    0    0   0   0    1.0  
2       0    0    0   0   0    1.0  
3       0    0    0   0   0    1.0  
4       0    0    0   0   0    1.0  
...   ...  ...  ...  ..  ..    ...  
5479    0    0    0   0   0   -1.0  
5480    0    0    0   0   0   -1.0  
5481    0    0    0   0   0   -1.0  
5482    0    0    0   0   0   -1.0  
5483    0    0    0   0   0   -1.0  

[5484 rows x 7795 columns]

In [110]:
review_DTM['label'].value_counts()

-1.0    2932
 1.0    2552
Name: label, dtype: int64

In [112]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [113]:
trn, test=train_test_split(review_DTM,test_size=0.2, shuffle=True, random_state=11)

In [114]:
trn_x = trn.drop('label', axis=1)
trn_y = trn['label']

In [115]:
multiNB = MultinomialNB()
multiNB.fit(trn_x, trn_y)

MultinomialNB()

In [116]:
multiNB.score(trn_x, trn_y)

0.8753134260314566

In [117]:
test_x = test.drop('label', axis=1)
test_y = test['label']

pred_y = multiNB.predict(test_x)

In [118]:
multiNB.score(test_x, test_y)

0.6025524156791249

In [119]:
from sklearn.metrics import classification_report

print(classification_report(test_y, pred_y, target_names=['하락','상승']))

              precision    recall  f1-score   support

          하락       0.62      0.66      0.64       588
          상승       0.58      0.53      0.55       509

    accuracy                           0.60      1097
   macro avg       0.60      0.60      0.60      1097
weighted avg       0.60      0.60      0.60      1097



# TF-IDF

In [127]:
import numpy as np

In [124]:
vect = CountVectorizer()
X_train_TF = vect.fit_transform(news_list) 

In [125]:
tf = pd.DataFrame(X_train_TF.toarray(), columns = vect.get_feature_names())

In [128]:
D = len(tf)
df = tf.astype(bool).sum(axis=0)
idf = np.log((D+1) / (df+1)) + 1 

In [129]:
tfidf = tf * idf                      
tfidf = tfidf / np.linalg.norm(tfidf, axis=1, keepdims=True)

In [130]:
tfidf

가격   가고   가구  가까운  가까워서  가까워졌  가까워졌다  가까이   가나   가는  ...   힐링   힐스  \
0     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
4     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...  ...  ...   ...   ...    ...  ...  ...  ...  ...  ...  ...   
5479  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
5480  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
5481  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
5482  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   
5483  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0   

      힐스테이트   힘껏   힘든  힘들까  힘들어  힘쓰는   힘찬   힙합  
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  ...  
5479    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5480    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5481    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5482    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5483    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5484 rows x 7794 columns]

In [132]:
tfidf['label'] = data['label']

In [133]:
tfidf['label'].value_counts()

-1.0    2932
 1.0    2552
Name: label, dtype: int64

In [138]:
tfidf

가격   가고   가구  가까운  가까워서  가까워졌  가까워졌다  가까이   가나   가는  ...   힐스  힐스테이트  \
0     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
1     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
2     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
3     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
4     0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
...   ...  ...  ...  ...   ...   ...    ...  ...  ...  ...  ...  ...    ...   
5479  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
5480  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
5481  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
5482  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   
5483  0.0  0.0  0.0  0.0   0.0   0.0    0.0  0.0  0.0  0.0  ...  0.0    0.0   

       힘껏   힘든  힘들까  힘들어  힘쓰는   힘찬   힙합  label  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
...   ...  ...  ...  ...  ...  ...  ...    ...  
5479  0.0  0.0  0.0  0.0  0.0  0.0  0.0   -1.0  
5480  0.0  0.0  0.0  0.0  0.0  0.0  0.0   -1.0  
5481  0.0  0.0  0.0  0.0  0.0  0.0  0.0   -1.0  
5482  0.0  0.0  0.0  0.0  0.0  0.0  0.0   -1.0  
5483  0.0  0.0  0.0  0.0  0.0  0.0  0.0   -1.0  

[5484 rows x 7795 columns]

In [137]:
tfidf.isna().sum()

가격       1
가고       1
가구       1
가까운      1
가까워서     1
        ..
힘들어      1
힘쓰는      1
힘찬       1
힙합       1
label    0
Length: 7795, dtype: int64

In [143]:
tfidf=tfidf.dropna()

In [144]:
trn, test=train_test_split(tfidf,test_size=0.3, shuffle=True, random_state=11)

In [145]:
trn_x = trn.drop('label', axis=1)
trn_y = trn['label']

In [146]:
multiNB = MultinomialNB()
multiNB.fit(trn_x, trn_y)

MultinomialNB()

In [147]:
multiNB.score(trn_x, trn_y)

0.8697238144867119

In [148]:
test_x = test.drop('label', axis=1)
test_y = test['label']

pred_y = multiNB.predict(test_x)

In [149]:
multiNB.score(test_x, test_y)

0.5677811550151975

In [150]:
from sklearn.metrics import classification_report

print(classification_report(test_y, pred_y, target_names=['하락','상승']))

              precision    recall  f1-score   support

          하락       0.56      0.76      0.65       858
          상승       0.58      0.36      0.44       787

    accuracy                           0.57      1645
   macro avg       0.57      0.56      0.55      1645
weighted avg       0.57      0.57      0.55      1645

